// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: NodeAgent/NodeAgent.proto

package NodeAgent

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	ComMessage "github.com/lyesteven/go-framework/pb/ComMessage"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SingleServiceListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string             `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	CbsType     ComMessage.CBSType `protobuf:"varint,2,opt,name=cbsType,proto3,enum=ComMessage.CBSType" json:"cbsType,omitempty"`
}

func (x *SingleServiceListReq) Reset() {
	*x = SingleServiceListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodeAgent_NodeAgent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleServiceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleServiceListReq) ProtoMessage() {}

func (x *SingleServiceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_NodeAgent_NodeAgent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleServiceListReq.ProtoReflect.Descriptor instead.
func (*SingleServiceListReq) Descriptor() ([]byte, []int) {
	return file_NodeAgent_NodeAgent_proto_rawDescGZIP(), []int{0}
}

func (x *SingleServiceListReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SingleServiceListReq) GetCbsType() ComMessage.CBSType {
	if x != nil {
		return x.CbsType
	}
	return ComMessage.CBSType_Own
}

type SingleServiceListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName    string         `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	ServiceVersion int64          `protobuf:"varint,2,opt,name=ServiceVersion,proto3" json:"ServiceVersion,omitempty"`
	ServiceList    []*ServiceInfo `protobuf:"bytes,3,rep,name=ServiceList,proto3" json:"ServiceList,omitempty"`
}

func (x *SingleServiceListRsp) Reset() {
	*x = SingleServiceListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodeAgent_NodeAgent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleServiceListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleServiceListRsp) ProtoMessage() {}

func (x *SingleServiceListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_NodeAgent_NodeAgent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleServiceListRsp.ProtoReflect.Descriptor instead.
func (*SingleServiceListRsp) Descriptor() ([]byte, []int) {
	return file_NodeAgent_NodeAgent_proto_rawDescGZIP(), []int{1}
}

func (x *SingleServiceListRsp) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SingleServiceListRsp) GetServiceVersion() int64 {
	if x != nil {
		return x.ServiceVersion
	}
	return 0
}

func (x *SingleServiceListRsp) GetServiceList() []*ServiceInfo {
	if x != nil {
		return x.ServiceList
	}
	return nil
}

type ServicesChangeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckList []*ServicesList `protobuf:"bytes,1,rep,name=CheckList,proto3" json:"CheckList,omitempty"`
}

func (x *ServicesChangeListReq) Reset() {
	*x = ServicesChangeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodeAgent_NodeAgent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesChangeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesChangeListReq) ProtoMessage() {}

func (x *ServicesChangeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_NodeAgent_NodeAgent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesChangeListReq.ProtoReflect.Descriptor instead.
func (*ServicesChangeListReq) Descriptor() ([]byte, []int) {
	return file_NodeAgent_NodeAgent_proto_rawDescGZIP(), []int{2}
}

func (x *ServicesChangeListReq) GetCheckList() []*ServicesList {
	if x != nil {
		return x.CheckList
	}
	return nil
}

type ServicesChangeListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangeList []*ServicesList `protobuf:"bytes,1,rep,name=ChangeList,proto3" json:"ChangeList,omitempty"`
}

func (x *ServicesChangeListRsp) Reset() {
	*x = ServicesChangeListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodeAgent_NodeAgent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesChangeListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesChangeListRsp) ProtoMessage() {}

func (x *ServicesChangeListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_NodeAgent_NodeAgent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesChangeListRsp.ProtoReflect.Descriptor instead.
func (*ServicesChangeListRsp) Descriptor() ([]byte, []int) {
	return file_NodeAgent_NodeAgent_proto_rawDescGZIP(), []int{3}
}

func (x *ServicesChangeListRsp) GetChangeList() []*ServicesList {
	if x != nil {
		return x.ChangeList
	}
	return nil
}

type ServicesList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName    string             `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	ServiceVersion string             `protobuf:"bytes,2,opt,name=ServiceVersion,proto3" json:"ServiceVersion,omitempty"`
	Info           []*ServiceInfo     `protobuf:"bytes,3,rep,name=Info,proto3" json:"Info,omitempty"`
	CbsType        ComMessage.CBSType `protobuf:"varint,4,opt,name=cbsType,proto3,enum=ComMessage.CBSType" json:"cbsType,omitempty"`
}

func (x *ServicesList) Reset() {
	*x = ServicesList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodeAgent_NodeAgent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesList) ProtoMessage() {}

func (x *ServicesList) ProtoReflect() protoreflect.Message {
	mi := &file_NodeAgent_NodeAgent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesList.ProtoReflect.Descriptor instead.
func (*ServicesList) Descriptor() ([]byte, []int) {
	return file_NodeAgent_NodeAgent_proto_rawDescGZIP(), []int{4}
}

func (x *ServicesList) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServicesList) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *ServicesList) GetInfo() []*ServiceInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ServicesList) GetCbsType() ComMessage.CBSType {
	if x != nil {
		return x.CbsType
	}
	return ComMessage.CBSType_Own
}

type ServiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceID     string `protobuf:"bytes,1,opt,name=ServiceID,proto3" json:"ServiceID,omitempty"`
	ServiceIP     string `protobuf:"bytes,2,opt,name=ServiceIP,proto3" json:"ServiceIP,omitempty"`
	ServicePort   int64  `protobuf:"varint,3,opt,name=ServicePort,proto3" json:"ServicePort,omitempty"`
	ServiceStatus string `protobuf:"bytes,4,opt,name=ServiceStatus,proto3" json:"ServiceStatus,omitempty"`
	PackageName   string `protobuf:"bytes,5,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_NodeAgent_NodeAgent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_NodeAgent_NodeAgent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_NodeAgent_NodeAgent_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceInfo) GetServiceID() string {
	if x != nil {
		return x.ServiceID
	}
	return ""
}

func (x *ServiceInfo) GetServiceIP() string {
	if x != nil {
		return x.ServiceIP
	}
	return ""
}

func (x *ServiceInfo) GetServicePort() int64 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

func (x *ServiceInfo) GetServiceStatus() string {
	if x != nil {
		return x.ServiceStatus
	}
	return ""
}

func (x *ServiceInfo) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

var File_NodeAgent_NodeAgent_proto protoreflect.FileDescriptor

var file_NodeAgent_NodeAgent_proto_rawDesc = []byte{
	0x0a, 0x19, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x4e, 0x6f, 0x64, 0x65,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x4e, 0x6f, 0x64,
	0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x43, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2f, 0x43, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x14, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a,
	0x07, 0x63, 0x62, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x43, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x42, 0x53, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x07, 0x63, 0x62, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x9a, 0x01, 0x0a,
	0x14, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x38, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x15, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x35, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x09,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x15, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x73, 0x70, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xb3, 0x01, 0x0a, 0x0c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26,
	0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x62, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x43, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x43, 0x42, 0x53, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x63, 0x62, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x50, 0x12, 0x20, 0x0a,
	0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12,
	0x24, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0xd4, 0x01, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x1f, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x20, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0e,
	0x5a, 0x0c, 0x70, 0x62, 0x2f, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_NodeAgent_NodeAgent_proto_rawDescOnce sync.Once
	file_NodeAgent_NodeAgent_proto_rawDescData = file_NodeAgent_NodeAgent_proto_rawDesc
)

func file_NodeAgent_NodeAgent_proto_rawDescGZIP() []byte {
	file_NodeAgent_NodeAgent_proto_rawDescOnce.Do(func() {
		file_NodeAgent_NodeAgent_proto_rawDescData = protoimpl.X.CompressGZIP(file_NodeAgent_NodeAgent_proto_rawDescData)
	})
	return file_NodeAgent_NodeAgent_proto_rawDescData
}

var file_NodeAgent_NodeAgent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_NodeAgent_NodeAgent_proto_goTypes = []interface{}{
	(*SingleServiceListReq)(nil),  // 0: NodeAgent.SingleServiceListReq
	(*SingleServiceListRsp)(nil),  // 1: NodeAgent.SingleServiceListRsp
	(*ServicesChangeListReq)(nil), // 2: NodeAgent.ServicesChangeListReq
	(*ServicesChangeListRsp)(nil), // 3: NodeAgent.ServicesChangeListRsp
	(*ServicesList)(nil),          // 4: NodeAgent.ServicesList
	(*ServiceInfo)(nil),           // 5: NodeAgent.ServiceInfo
	(ComMessage.CBSType)(0),       // 6: ComMessage.CBSType
}
var file_NodeAgent_NodeAgent_proto_depIdxs = []int32{
	6, // 0: NodeAgent.SingleServiceListReq.cbsType:type_name -> ComMessage.CBSType
	5, // 1: NodeAgent.SingleServiceListRsp.ServiceList:type_name -> NodeAgent.ServiceInfo
	4, // 2: NodeAgent.ServicesChangeListReq.CheckList:type_name -> NodeAgent.ServicesList
	4, // 3: NodeAgent.ServicesChangeListRsp.ChangeList:type_name -> NodeAgent.ServicesList
	5, // 4: NodeAgent.ServicesList.Info:type_name -> NodeAgent.ServiceInfo
	6, // 5: NodeAgent.ServicesList.cbsType:type_name -> ComMessage.CBSType
	0, // 6: NodeAgent.NodeAgent.Node_Agent_GetSingleServiceList:input_type -> NodeAgent.SingleServiceListReq
	2, // 7: NodeAgent.NodeAgent.Node_Agent_GetServicesChangeList:input_type -> NodeAgent.ServicesChangeListReq
	4, // 8: NodeAgent.NodeAgent.Node_Agent_GetSingleServiceList:output_type -> NodeAgent.ServicesList
	3, // 9: NodeAgent.NodeAgent.Node_Agent_GetServicesChangeList:output_type -> NodeAgent.ServicesChangeListRsp
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_NodeAgent_NodeAgent_proto_init() }
func file_NodeAgent_NodeAgent_proto_init() {
	if File_NodeAgent_NodeAgent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_NodeAgent_NodeAgent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleServiceListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodeAgent_NodeAgent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleServiceListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodeAgent_NodeAgent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesChangeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodeAgent_NodeAgent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesChangeListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodeAgent_NodeAgent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_NodeAgent_NodeAgent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_NodeAgent_NodeAgent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_NodeAgent_NodeAgent_proto_goTypes,
		DependencyIndexes: file_NodeAgent_NodeAgent_proto_depIdxs,
		MessageInfos:      file_NodeAgent_NodeAgent_proto_msgTypes,
	}.Build()
	File_NodeAgent_NodeAgent_proto = out.File
	file_NodeAgent_NodeAgent_proto_rawDesc = nil
	file_NodeAgent_NodeAgent_proto_goTypes = nil
	file_NodeAgent_NodeAgent_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeAgentClient interface {
	Node_Agent_GetSingleServiceList(ctx context.Context, in *SingleServiceListReq, opts ...grpc.CallOption) (*ServicesList, error)
	Node_Agent_GetServicesChangeList(ctx context.Context, in *ServicesChangeListReq, opts ...grpc.CallOption) (*ServicesChangeListRsp, error)
}

type nodeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentClient(cc grpc.ClientConnInterface) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) Node_Agent_GetSingleServiceList(ctx context.Context, in *SingleServiceListReq, opts ...grpc.CallOption) (*ServicesList, error) {
	out := new(ServicesList)
	err := c.cc.Invoke(ctx, "/NodeAgent.NodeAgent/Node_Agent_GetSingleServiceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Node_Agent_GetServicesChangeList(ctx context.Context, in *ServicesChangeListReq, opts ...grpc.CallOption) (*ServicesChangeListRsp, error) {
	out := new(ServicesChangeListRsp)
	err := c.cc.Invoke(ctx, "/NodeAgent.NodeAgent/Node_Agent_GetServicesChangeList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServer is the server API for NodeAgent service.
type NodeAgentServer interface {
	Node_Agent_GetSingleServiceList(context.Context, *SingleServiceListReq) (*ServicesList, error)
	Node_Agent_GetServicesChangeList(context.Context, *ServicesChangeListReq) (*ServicesChangeListRsp, error)
}

// UnimplementedNodeAgentServer can be embedded to have forward compatible implementations.
type UnimplementedNodeAgentServer struct {
}

func (*UnimplementedNodeAgentServer) Node_Agent_GetSingleServiceList(context.Context, *SingleServiceListReq) (*ServicesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Node_Agent_GetSingleServiceList not implemented")
}
func (*UnimplementedNodeAgentServer) Node_Agent_GetServicesChangeList(context.Context, *ServicesChangeListReq) (*ServicesChangeListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Node_Agent_GetServicesChangeList not implemented")
}

func RegisterNodeAgentServer(s *grpc.Server, srv NodeAgentServer) {
	s.RegisterService(&_NodeAgent_serviceDesc, srv)
}

func _NodeAgent_Node_Agent_GetSingleServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleServiceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Node_Agent_GetSingleServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeAgent.NodeAgent/Node_Agent_GetSingleServiceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Node_Agent_GetSingleServiceList(ctx, req.(*SingleServiceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Node_Agent_GetServicesChangeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesChangeListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Node_Agent_GetServicesChangeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeAgent.NodeAgent/Node_Agent_GetServicesChangeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Node_Agent_GetServicesChangeList(ctx, req.(*ServicesChangeListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NodeAgent.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Node_Agent_GetSingleServiceList",
			Handler:    _NodeAgent_Node_Agent_GetSingleServiceList_Handler,
		},
		{
			MethodName: "Node_Agent_GetServicesChangeList",
			Handler:    _NodeAgent_Node_Agent_GetServicesChangeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "NodeAgent/NodeAgent.proto",
}
