// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: ComMessage/ComMessage.proto

package ComMessage

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//call business system type
type CBSType int32

const (
	CBSType_Own  CBSType = 0
	CBSType_Base CBSType = 1
)

// Enum value maps for CBSType.
var (
	CBSType_name = map[int32]string{
		0: "Own",
		1: "Base",
	}
	CBSType_value = map[string]int32{
		"Own":  0,
		"Base": 1,
	}
)

func (x CBSType) Enum() *CBSType {
	p := new(CBSType)
	*p = x
	return p
}

func (x CBSType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CBSType) Descriptor() protoreflect.EnumDescriptor {
	return file_ComMessage_ComMessage_proto_enumTypes[0].Descriptor()
}

func (CBSType) Type() protoreflect.EnumType {
	return &file_ComMessage_ComMessage_proto_enumTypes[0]
}

func (x CBSType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CBSType.Descriptor instead.
func (CBSType) EnumDescriptor() ([]byte, []int) {
	return file_ComMessage_ComMessage_proto_rawDescGZIP(), []int{0}
}

var File_ComMessage_ComMessage_proto protoreflect.FileDescriptor

var file_ComMessage_ComMessage_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x43, 0x6f, 0x6d,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x43,
	0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x1c, 0x0a, 0x07, 0x43, 0x42, 0x53,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x42, 0x61, 0x73, 0x65, 0x10, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x62, 0x2f, 0x43, 0x6f,
	0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ComMessage_ComMessage_proto_rawDescOnce sync.Once
	file_ComMessage_ComMessage_proto_rawDescData = file_ComMessage_ComMessage_proto_rawDesc
)

func file_ComMessage_ComMessage_proto_rawDescGZIP() []byte {
	file_ComMessage_ComMessage_proto_rawDescOnce.Do(func() {
		file_ComMessage_ComMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_ComMessage_ComMessage_proto_rawDescData)
	})
	return file_ComMessage_ComMessage_proto_rawDescData
}

var file_ComMessage_ComMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ComMessage_ComMessage_proto_goTypes = []interface{}{
	(CBSType)(0), // 0: ComMessage.CBSType
}
var file_ComMessage_ComMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ComMessage_ComMessage_proto_init() }
func file_ComMessage_ComMessage_proto_init() {
	if File_ComMessage_ComMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ComMessage_ComMessage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ComMessage_ComMessage_proto_goTypes,
		DependencyIndexes: file_ComMessage_ComMessage_proto_depIdxs,
		EnumInfos:         file_ComMessage_ComMessage_proto_enumTypes,
	}.Build()
	File_ComMessage_ComMessage_proto = out.File
	file_ComMessage_ComMessage_proto_rawDesc = nil
	file_ComMessage_ComMessage_proto_goTypes = nil
	file_ComMessage_ComMessage_proto_depIdxs = nil
}
