// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.11.4
// source: AASMessage/AASMessage.proto

package AASMessage

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InvokeServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppKey      string `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"` // App提供
	AppVer      string `protobuf:"bytes,2,opt,name=appVer,proto3" json:"appVer,omitempty"` // App版本号
	Id          string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Token       string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`             //App提供
	UserType    int64  `protobuf:"varint,5,opt,name=userType,proto3" json:"userType,omitempty"`      // 判断是否验证token ‘33333’不验
	Data        string `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`               //App调用服务参数
	IdFromToken string `protobuf:"bytes,7,opt,name=idFromToken,proto3" json:"idFromToken,omitempty"` // 从token解密出的 id
	// 目前内部调用和外部调用用的是统一proto, 以下两个字段要保留   by jeffrey
	ServiceName string `protobuf:"bytes,8,opt,name=serviceName,proto3" json:"serviceName,omitempty"` //需要调用Service名称
	MethodName  string `protobuf:"bytes,9,opt,name=methodName,proto3" json:"methodName,omitempty"`   //需要调用方法名称
}

func (x *InvokeServiceRequest) Reset() {
	*x = InvokeServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AASMessage_AASMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServiceRequest) ProtoMessage() {}

func (x *InvokeServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AASMessage_AASMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServiceRequest.ProtoReflect.Descriptor instead.
func (*InvokeServiceRequest) Descriptor() ([]byte, []int) {
	return file_AASMessage_AASMessage_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeServiceRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *InvokeServiceRequest) GetAppVer() string {
	if x != nil {
		return x.AppVer
	}
	return ""
}

func (x *InvokeServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvokeServiceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InvokeServiceRequest) GetUserType() int64 {
	if x != nil {
		return x.UserType
	}
	return 0
}

func (x *InvokeServiceRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *InvokeServiceRequest) GetIdFromToken() string {
	if x != nil {
		return x.IdFromToken
	}
	return ""
}

func (x *InvokeServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *InvokeServiceRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

type InvokeServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceResponseData string `protobuf:"bytes,1,opt,name=serviceResponseData,proto3" json:"serviceResponseData,omitempty"` //Service返回结果
}

func (x *InvokeServiceResponse) Reset() {
	*x = InvokeServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AASMessage_AASMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeServiceResponse) ProtoMessage() {}

func (x *InvokeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AASMessage_AASMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeServiceResponse.ProtoReflect.Descriptor instead.
func (*InvokeServiceResponse) Descriptor() ([]byte, []int) {
	return file_AASMessage_AASMessage_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeServiceResponse) GetServiceResponseData() string {
	if x != nil {
		return x.ServiceResponseData
	}
	return ""
}

var File_AASMessage_AASMessage_proto protoreflect.FileDescriptor

var file_AASMessage_AASMessage_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x41, 0x41, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x41, 0x41, 0x53,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x41,
	0x41, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x80, 0x02, 0x0a, 0x14, 0x49, 0x6e,
	0x76, 0x6f, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70,
	0x70, 0x56, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x56,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x64, 0x46, 0x72,
	0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69,
	0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x15,
	0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x62, 0x2f, 0x41, 0x41,
	0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AASMessage_AASMessage_proto_rawDescOnce sync.Once
	file_AASMessage_AASMessage_proto_rawDescData = file_AASMessage_AASMessage_proto_rawDesc
)

func file_AASMessage_AASMessage_proto_rawDescGZIP() []byte {
	file_AASMessage_AASMessage_proto_rawDescOnce.Do(func() {
		file_AASMessage_AASMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_AASMessage_AASMessage_proto_rawDescData)
	})
	return file_AASMessage_AASMessage_proto_rawDescData
}

var file_AASMessage_AASMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AASMessage_AASMessage_proto_goTypes = []interface{}{
	(*InvokeServiceRequest)(nil),  // 0: AASMessage.InvokeServiceRequest
	(*InvokeServiceResponse)(nil), // 1: AASMessage.InvokeServiceResponse
}
var file_AASMessage_AASMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AASMessage_AASMessage_proto_init() }
func file_AASMessage_AASMessage_proto_init() {
	if File_AASMessage_AASMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AASMessage_AASMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AASMessage_AASMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AASMessage_AASMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AASMessage_AASMessage_proto_goTypes,
		DependencyIndexes: file_AASMessage_AASMessage_proto_depIdxs,
		MessageInfos:      file_AASMessage_AASMessage_proto_msgTypes,
	}.Build()
	File_AASMessage_AASMessage_proto = out.File
	file_AASMessage_AASMessage_proto_rawDesc = nil
	file_AASMessage_AASMessage_proto_goTypes = nil
	file_AASMessage_AASMessage_proto_depIdxs = nil
}
